/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientUploadRouteImport } from './routes/patient.upload'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPricesRouteImport } from './routes/patient.prices'
import { Route as PatientPaymentRouteImport } from './routes/patient.payment'
import { Route as PatientMedicinesRouteImport } from './routes/patient.medicines'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as PatientDispenseRouteImport } from './routes/patient.dispense'
import { Route as PatientAiAssistantRouteImport } from './routes/patient.ai-assistant'

const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientUploadRoute = PatientUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPricesRoute = PatientPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPaymentRoute = PatientPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => PatientRoute,
} as any)
const PatientMedicinesRoute = PatientMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDispenseRoute = PatientDispenseRouteImport.update({
  id: '/dispense',
  path: '/dispense',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAiAssistantRoute = PatientAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/ai-assistant': typeof PatientAiAssistantRoute
  '/patient/dispense': typeof PatientDispenseRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/medicines': typeof PatientMedicinesRoute
  '/patient/payment': typeof PatientPaymentRoute
  '/patient/prices': typeof PatientPricesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRoute
  '/patient/ai-assistant': typeof PatientAiAssistantRoute
  '/patient/dispense': typeof PatientDispenseRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/medicines': typeof PatientMedicinesRoute
  '/patient/payment': typeof PatientPaymentRoute
  '/patient/prices': typeof PatientPricesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/doctor': typeof DoctorRoute
  '/patient': typeof PatientRouteWithChildren
  '/patient/ai-assistant': typeof PatientAiAssistantRoute
  '/patient/dispense': typeof PatientDispenseRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/medicines': typeof PatientMedicinesRoute
  '/patient/payment': typeof PatientPaymentRoute
  '/patient/prices': typeof PatientPricesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/doctor'
    | '/patient'
    | '/patient/ai-assistant'
    | '/patient/dispense'
    | '/patient/history'
    | '/patient/medicines'
    | '/patient/payment'
    | '/patient/prices'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/upload'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/doctor'
    | '/patient/ai-assistant'
    | '/patient/dispense'
    | '/patient/history'
    | '/patient/medicines'
    | '/patient/payment'
    | '/patient/prices'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/upload'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/doctor'
    | '/patient'
    | '/patient/ai-assistant'
    | '/patient/dispense'
    | '/patient/history'
    | '/patient/medicines'
    | '/patient/payment'
    | '/patient/prices'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/upload'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DoctorRoute: typeof DoctorRoute
  PatientRoute: typeof PatientRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/upload': {
      id: '/patient/upload'
      path: '/upload'
      fullPath: '/patient/upload'
      preLoaderRoute: typeof PatientUploadRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prices': {
      id: '/patient/prices'
      path: '/prices'
      fullPath: '/patient/prices'
      preLoaderRoute: typeof PatientPricesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/payment': {
      id: '/patient/payment'
      path: '/payment'
      fullPath: '/patient/payment'
      preLoaderRoute: typeof PatientPaymentRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/medicines': {
      id: '/patient/medicines'
      path: '/medicines'
      fullPath: '/patient/medicines'
      preLoaderRoute: typeof PatientMedicinesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/dispense': {
      id: '/patient/dispense'
      path: '/dispense'
      fullPath: '/patient/dispense'
      preLoaderRoute: typeof PatientDispenseRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/ai-assistant': {
      id: '/patient/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/patient/ai-assistant'
      preLoaderRoute: typeof PatientAiAssistantRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface PatientRouteChildren {
  PatientAiAssistantRoute: typeof PatientAiAssistantRoute
  PatientDispenseRoute: typeof PatientDispenseRoute
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientMedicinesRoute: typeof PatientMedicinesRoute
  PatientPaymentRoute: typeof PatientPaymentRoute
  PatientPricesRoute: typeof PatientPricesRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientUploadRoute: typeof PatientUploadRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAiAssistantRoute: PatientAiAssistantRoute,
  PatientDispenseRoute: PatientDispenseRoute,
  PatientHistoryRoute: PatientHistoryRoute,
  PatientMedicinesRoute: PatientMedicinesRoute,
  PatientPaymentRoute: PatientPaymentRoute,
  PatientPricesRoute: PatientPricesRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientUploadRoute: PatientUploadRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DoctorRoute: DoctorRoute,
  PatientRoute: PatientRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
